# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-05 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='label',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
